---
title: "Tarea 1. Macroeconomía"
author: "Marco Méndez Atienza"
date: "`r format(Sys.time(), '%d de %B de %Y')`"
output: pdf_document
---

## Problema 8.2.

**El Ingreso promedio de los agricultores es menor al ingreso promedio de los no agricultores, pero fluctúa más año con año. Dado esto, ¿cómo la Hipótesis del Ingreso Permanente predice que las funciones de consumo estimado entre ambos grupos difieren?**

Sabemos que, en promedio, el ingreso transitorio es igual a cero y que el ingreso promedio puede ser interpretado como el ingreso permanente promedio. Así, el problema indica que el ingreso permanente de los agricultores es menor al de los no agricultores, esto es:

\begin{equation}
\bar{Y}_{A}^P < \bar{Y}_{NA}^P 
\end{equation}

Es decir, el hecho de que el ingreso de los agricultores fluctúe más año con año implica que la varianza del ingreso transitorio de los agricultores es mayor a la de los no agricultores: $Var(Y^T_{A}) > Var(Y_{NA}^T)$.

Considere el siguiente modelo de regresión:

\begin{equation}
C_{i} = a + bY_{i} + e_{i}
\end{equation}

Donde $C_{i}$ es el consumo actual y, de acuerdo a la HIP, determinado por completo por $Y^P$, tal que $C = Y^P$. Además, $Y_{i}$ es el ingreso actual, que es la suma del ingreso permanente y el transitorio, tal que $Y = Y^P + Y^T$.

Sabemos que el estimador de b bajo Mínimos Cuadrados Ordinarios (MCO) tiene la forma:

\begin{equation}
\hat{b} = \frac{Var(Y^P)}{Var(Y^P) + Var(Y^T)}
\end{equation}

$Var(Y_{A}^T)>Var(Y_{NA}^T)$ implica que **el coeficiente estimado $\hat{b}$ de la pendiente es menor para los agricultores que para los no agricultores**. Esto significa que el impacto estimado de un incremento marginal en el ingreso actual sobre el consumo es más pequeño en el caso de los agricultores. De acuerdo a la HIP, esto se debe a que el incremento es mucho más probable de provenir del ingreso transitorio para los agricultores.

Por otra parte, el estimador MCO para el término constante toma la forma:

\begin{equation}
\hat{a} = (1-\hat{b})\bar{Y}^P
\end{equation}

Los agricultores, en promedio, tienen un ingreso permanente menor a los no agricultores. Sin embargo, como se mencionó, el estimador $\hat{b}$ también es menor para los agricultores, por lo que **el efecto sobre el estimador $\hat{a}$ es ambiguo.**

## Problema 8.4

**En el modelo de la Sección 8.2, la incertidumbre sobre el ingreso futuro no afecta al consumo. ¿Significa esto que la incertidumbre no afecta la utilidad vitalicia esperada?**

Sabemos que la utilidad esperada vitalicia esperada es:

\begin{equation}
E_{1}[U] = E_{1}[\sum_{t=1}^{T} (C_{t} - \frac{a}{2}C_{t}^2)]
\end{equation}

donde $a > 0$. Esto puede ser reescrito como:

\begin{equation}
E_{1}[U] = \sum_{t=1}^{T}(E_{1}[C_{t}] - \frac{a}{2}E_{1}[C_{t}^{2}])
\end{equation}

Dado que el valor esperado del consumo en todos los periodos es $C_{1}$, esto es:

\begin{equation}
E_{1}[C_{t}]=C_{1}
\end{equation}

Que puede escribirse:

\begin{equation}
C_{t} = C_{1} + e_{t}
\end{equation}

donde $E_{1}[e_{t}] = 0$ y $Var(e_{t} = \sigma_{e_{t}}^2)$. La ecuación (8) se cumple para todos los periodos; entonces, sustituyéndola en la ecuación (6):

\begin{equation}
E_{1}[U] = \sum_{t=1}^T(E_{1}[C_{1} + e_{t}]-\frac{a}{2}E_{1}[(C_{1} + e_{t})^2]
\end{equation}

Como $E_{1}[C_{1}] = C_{1}$ y $E_{1}[e_{t}] = 0$:

\begin{equation}
E_{1}[U] = \sum_{t=1}^{T}(C_{1} - \frac{a}{2}C_{1}^{2} - \frac{a}{2}E_{1}[e_{t}^{2}])
\end{equation}

Como $E_{1}[e_{t}^{2}] = Var(e_{t}) = \sigma_{e_{t}}^{2}$, la ecuación (10) puede ser escrita:

\begin{equation}
E_{1}[U] = \sum_{t=1}^{T}(C_{1} - \frac{a}{2}C_{1}^{2} - \frac{a}{2}\sigma_{e_{t}}^{2})
\end{equation}

Si $C_{t} = C_{1}$ con seguridad, tal que $e_{t} = 0$ y $Var(e_{t}) = \sigma_{e_{t}}^{2} = 0$, la utilidad vitalicia es:

\begin{equation}
U = \sum_{t=1}^{T}(C_{1} - \frac{a}{2}C_{1}^{2})
\end{equation}

Es decir, se comparan las ecuaciones con incertidumbre (11) y con certidumbre (12): como $C_{1}$ es el mismo con o sin incertidumbre, **la utilidad bajo incertidumbre (siempre que $Var(e_{t}) = \sigma_{e_{t}}^{2} > 0$) será menor.**
